#### Ansible inventory.

resource "local_file" "ansible_inventory" {
  depends_on = [ module.vsi ]
  content = <<-DOC
all:
  hosts:
    db_host:
      ansible_host: "${data.ibm_is_instance.vsi.primary_network_interface[0].primary_ip[0].address}"
    DOC
  filename = "ansible/inventory.yml"
}

#### Export Terraform variable values to an Ansible var_file
resource "local_file" "app_ansible-vars" {
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.SAP_SID}"
sap_ci_instance_number: "${var.SAP_CI_INSTANCE_NUMBER}"
sap_ascs_instance_number: "${var.SAP_ASCS_INSTANCE_NUMBER}"
sap_main_password: "${var.SAP_MAIN_PASSWORD}"
sap_profile: "${var.PROFILE}"

#Kits paths
kit_sapcar_file: "${var.KIT_SAPCAR_FILE}"
kit_swpm_file: "${var.KIT_SWPM_FILE}"
kit_saphostagent_file: "${var.KIT_SAPHOSTAGENT_FILE}"
kit_sapexe_file: "${var.KIT_SAPEXE_FILE}"
kit_sapexedb_file: "${var.KIT_SAPEXEDB_FILE}"
kit_igsexe_file: "${var.KIT_IGSEXE_FILE}"
kit_igshelper_file: "${var.KIT_IGSHELPER_FILE}"
kit_export_dir: "${var.KIT_EXPORT_DIR}"
kit_db2_dir: "${var.KIT_DB2_DIR}"
kit_db2client_dir: "${var.KIT_DB2CLIENT_DIR}"
...
    DOC
  filename = "ansible/sapnwdb2-vars.yml"
}
