#### Ansible inventory.

resource "local_file" "ansible_inventory" {
  depends_on = [ module.vsi ]
  content = <<-DOC
all:
  hosts:
    db_host:
      ansible_host: "${data.ibm_is_instance.vsi.primary_network_interface[0].primary_ip[0].address}"
    DOC
  filename = "ansible/inventory.yml"
}

#### Export Terraform variable values to an Ansible var_file
resource "local_file" "app_ansible-vars" {
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.sap_sid}"
sap_ci_instance_number: "${var.sap_ci_instance_number}"
sap_ascs_instance_number: "${var.sap_ascs_instance_number}"
sap_main_password: "${var.sap_main_password}"
sap_profile: "${var.PROFILE}"

#Kits paths
kit_sapcar_file: "${var.kit_sapcar_file}"
kit_swpm_file: "${var.kit_swpm_file}"
kit_saphotagent_file: "${var.kit_saphotagent_file}"
kit_sapexe_file: "${var.kit_sapexe_file}"
kit_sapexedb_file: "${var.kit_sapexedb_file}"
kit_igsexe_file: "${var.kit_igsexe_file}"
kit_igshelper_file: "${var.kit_igshelper_file}"
kit_export_dir: "${var.kit_export_dir}"
kit_db2_dir: "${var.kit_db2_dir}"
kit_db2client_dir: "${var.kit_db2client_dir}"
...
    DOC
  filename = "ansible/sapnwdb2-vars.yml"
}
