---
# SAP Notes:
# - 2772999 - Red Hat Enterprise Linux 8.x: Installation and Configuration (v22)
# - 2578899 - SUSE Linux Enterprise Server 15: Installation Note (v44)

- name: Reboot target host
  reboot:
    connect_timeout: 5
    post_reboot_delay: 10
...
