---
- name: Import install kit
  include_tasks: "install_kit.yml"

- name: Generate parameter file for sapinst
  template:
      src: sapinst.cfg
      dest: "{{ sap_kit }}/inifile.params"

- name: Check if the Application Server was already installed
  stat:
    path: "/sapmnt/{{ sap_sid|upper }}/exe/uc/linuxx86_64/SAPCAR"
  register: install_status

- name: Working at SAP installation ...
  shell: "{{ sap_kit }}/swpm/sapinst SAPINST_INPUT_PARAMETERS_URL={{ sap_kit }}/inifile.params SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false"
  async: 10800
  poll: 0
  register: sap_inst_status
  when: not install_status.stat.exists

# SAP Note:
# - 2570458 - DB6: Depooling report RUTPOADAPT fails with SQL -912 (v1)

- name: Attempt to disable the registry setting DB2_AVOID_LOCK_ESCALATION - workaround from SAP Note 2570458
  shell: "su - db2{{ sap_sid|lower }} -c 'db2set DB2_AVOID_LOCK_ESCALATION=FALSE'"
  register: db2_avlockesc
  retries: 1080
  delay: 10
  until: db2_avlockesc.rc == 0
  when: (ansible_facts['os_family'] == "Suse" and ansible_facts['distribution_major_version'] == "15" or ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") and not install_status.stat.exists

- name: Wait for asynchronous job to end
  ansible.builtin.async_status:
    jid: '{{ sap_inst_status.ansible_job_id }}'
  register: job_result
  until: job_result.finished
  retries: 1100
  delay: 25
  when: sap_inst_status is defined

- name: Re-enable the registry setting DB2_AVOID_LOCK_ESCALATION - workaround from SAP Note 2570458
  shell: "su - db2{{ sap_sid|lower }} -c 'db2set DB2_AVOID_LOCK_ESCALATION='"
  when: (ansible_facts['os_family'] == "Suse" and ansible_facts['distribution_major_version'] == "15" or ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") and not install_status.stat.exists

- name: Cleanup
  file:
    path: "{{ sap_kit }}"
    state: absent
...
