---
# SAP Notes:
# - 2369910 - SAP Software on Linux: General information (v17)
# - 2772999 - Red Hat Enterprise Linux 8.x: Installation and Configuration (v22)
# - 2578899 - SUSE Linux Enterprise Server 15: Installation Note (v44)
# - 611361 - Hostnames of SAP ABAP Platform servers (v12)

- name: Get short hostname
  command: hostname -s
  register: sap_short_hostname
  changed_when: False

- name: Get FQDN
  set_fact:
    sap_host_fqdn: "{{ ansible_fqdn }}"

- name: Check if hostname has 13 or less characters as per SAP requirement
  fail:
    msg: "Hostname {{ sap_short_hostname.stdout }} has more than 13 characters"
  when:  sap_short_hostname.stdout|length > 13

- name: Line to be added in /etc/hosts if FQDN is set
  set_fact:
    line_to_add: "{{ ansible_default_ipv4.address }} {{ sap_host_fqdn }} {{ sap_short_hostname.stdout }}"
  when: sap_short_hostname.stdout != sap_host_fqdn

- name: Line to be added in /etc/hosts if FQDN is not set
  set_fact:
    line_to_add: "{{ ansible_default_ipv4.address }} {{ sap_short_hostname.stdout }}"
  when: sap_short_hostname.stdout == sap_host_fqdn

- name: Enable hostname resolve to internal IP
  lineinfile:
    path: /etc/hosts
    line: "{{ line_to_add }}"
...
