---
# SAP Notes:
# - 2772999 - Red Hat Enterprise Linux 8.x: Installation and Configuration (v22)
# - 1771258 - Linux: User and system resource limits (v6)
- name: Set nofile limit for sapsys group
  pam_limits:
    dest: /etc/security/limits.d/99-sap.conf
    domain: "@sapsys"
    limit_item: nofile
    limit_type: "{{ ltype }}"
    value: "1048576"
  loop:
    - soft
    - hard
  loop_control:
    loop_var: ltype

- name: Set nofile limit for db{{ sap_sid|lower }}adm group
  pam_limits:
    dest: /etc/security/limits.d/99-sap.conf
    domain: "@db{{ sap_sid|lower }}adm"
    limit_item: nofile
    limit_type: "{{ ltype }}"
    value: "1048576"
  loop:
    - soft
    - hard
  loop_control:
    loop_var: ltype     

- name: Set nproc limit for sapsys group
  pam_limits:
    dest: /etc/security/limits.d/99-sap.conf
    domain: "@sapsys"
    limit_item: nproc
    limit_type: "{{ ltype }}"
    value: unlimited
  loop:
    - soft
    - hard
  loop_control:
    loop_var: ltype

- name: Set nproc limit for db{{ sap_sid|lower }}adm group
  pam_limits:
    dest: /etc/security/limits.d/99-sap.conf
    domain: "@db{{ sap_sid|lower }}adm"
    limit_item: nproc
    limit_type: "{{ ltype }}"
    value: unlimited
  loop:
    - soft
    - hard
  loop_control:
    loop_var: ltype

...