---
#Disk size config
data_disk_size: "256.00 GB"
log_disk_size: "32.00 GB"
arch_disk_size: "64.00 GB"
sap_disk_size: "128.00 GB"
swap_disk_size: "40.00 GB"

#Logical volume size config
db2software_lv_size: "5g"
db2_lv_size: "2g"
db2dump_lv_size: "5g"
sapdata1_lv_size: "25g"
sapdata2_lv_size: "25g"
sapdata3_lv_size: "25g"
sapdata4_lv_size: "25g"
saptmp1_lv_size: "5g"
saptmp2_lv_size: "5g"
saptmp3_lv_size: "5g"
saptmp4_lv_size: "5g"
log_lv_size: "25g"
archlog_lv_size: "50g"
usrsap_lv_size: "5g"
sap_lv_size: "20g"
sapmnt_lv_size: "20g"
saptrans_lv_size: "20g"

# SWAP sizing:
# - SAP notes: 
#   - 2369910 - SAP Software on Linux: General information (v17)
#   - 2578899 - SUSE Linux Enterprise Server 15: Installation Note (v44)
#   - 1597355 - Swap-space recommendation for Linux (v3)
# Commented until terraform code update
# SWAP size GB 
# swap_lv:
#   - size: 64
#     ram_min: 32
#     ram_max: 63
#   - size: 96
#     ram_min: 64
#     ram_max: 127
#   - size: 128
#     ram_min: 128
#     ram_max: 255
#   - size: 160
#     ram_min: 256
#     ram_max: 511
#   - size: 192
#     ram_min: 512
#     ram_max: 1023
#   - size: 224
#     ram_min: 1024
#     ram_max: 2047
#   - size: 256
#     ram_min: 2048
#     ram_max: 4095
#   - size: 288
#     ram_min: 4096
#     ram_max: 8191
#   - size: 320
#     ram_min: 8192
#     ram_max: 20000
# SWAP size GB 
swap_lv:
  - size: 30
    ram_min: 32
    ram_max: 63
  - size: 30
    ram_min: 64
    ram_max: 127
  - size: 30
    ram_min: 128
    ram_max: 255
  - size: 30
    ram_min: 256
    ram_max: 511
  - size: 30
    ram_min: 512
    ram_max: 1023
  - size: 30
    ram_min: 1024
    ram_max: 2047
  - size: 30
    ram_min: 2048
    ram_max: 4095
  - size: 30
    ram_min: 4096
    ram_max: 8191
  - size: 30
    ram_min: 8192
    ram_max: 20000
...
