---
# TMPFS sizing
# SAP Notes:
# - 2772999 - Red Hat Enterprise Linux 8.x: Installation and Configuration (v22)
# - 2578899 - SUSE Linux Enterprise Server 15: Installation Note (v44)
# - 941735 - SAP memory management system for 64-bit Linux systems (v11)

- name: Get the RAM size
  set_fact:
    app_ram_g: "{{ sap_profile.split('-')[1].split('x')[1] }}"

- name: Compute the swap logical volume size for RAM lower than 32 GB
  set_fact:
    swap_lv_size_g: "{{ app_ram_g | int * 2 }}"
  when: app_ram_g | int < 32

- name: Compute the swap logical volume size for RAM higher than 32 GB
  set_fact:
    swap_lv_size_g: "{{ item.size }}"
  loop: "{{ swap_lv }}"
  when: (app_ram_g | int > 32) and (app_ram_g | int >= item.ram_min) and (app_ram_g | int <= item.ram_min)

- name: Compute the swap logical volume size for RAM higher than 32 GB
  set_fact:
    swap_lv_size_g: "{{ swap_data.size }}"
  loop: "{{ swap_lv }}"
  loop_control:
    loop_var: swap_data
  when: (app_ram_g | int > 32) and (app_ram_g | int >= swap_data.ram_min) and (app_ram_g | int <= swap_data.ram_min)

- name: Get the current tmpfs mount data
  shell: set -o pipefail && df -h |grep tmpfs|grep shm| awk '{print $2}'
  args:
    executable: /bin/bash
  register: tmpfs_crt_data
  when: swap_lv_size_g is defined

- name: Compute tmpfs size
  set_fact:
    tmpfs_size_g: "{{ ((app_ram_g | float + swap_lv_size_g | float) * 0.75) | round | int }}"

- name: Current tmpfs size
  set_fact:
    crt_tmpfs_size_g: "{{ tmpfs_crt_data.stdout | float | round | int }}"

- name: Remount tmpfs
  mount:
    path: /dev/shm
    src: tmpfs
    fstype: tmpfs
    opts: "size={{ tmpfs_size_g }}G,rw,nosuid,nodev 0 0"
    state: remounted
  when: (crt_tmpfs_size_g | float - tmpfs_size_g | float) | abs > 1

- name: Add tmpfs device to /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^/dev/shm (.*)$"
    line: "tmpfs /dev/shm tmpfs size={{ tmpfs_size_g }}G,rw,nosuid,nodev 0 0"
...
